[package]

name = "challenge3"
version = "0.0.1"
authors = ["Steffen Imhof <mail@steffen-imhof.de>"]

[dependencies.codec]
path = "../../modules/codec"

[dependencies.challenge2]
path = "../challenge2"
